### PR TITLE
T/28: Fix selected item cycling when only one item in mentions view.

### LINKED ISSUE #28: Up/down arrows are locked
I recorded pressing:

* right (moves caret),
* left (moves caret),
* top/bottom (irreversibly changes item selection, locks the caret).

Apr-03-2019 11-25-21

I don't think that up/down should be locked. But if you think it should, then at least the item selection should not be changed (if there's just one item).

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: The single item in mentions view will be always highlighted when using arrow up or arrow down. Closes #28.

---

### Additional information

* The selection focus is now properly cycled.
* ~This PR also includes fix for mention UI broken test (it looks like some merge conflict wasn't properly resolved after #41 PR (flattens the Mention UI - the `listView` was removed).~ Cherry picked to master.

### CODE REVIEW

**Comment by mlewand** [comment]
Hijacking the review 🏃

File: tests/mentionui.js [hunk 1]
```diff
@@ -897,6 +897,49 @@ describe( 'MentionUI', () => {
...
+						stopPropagation: sinon.spy()
+					};
+
+					model.change( writer => {
+						writer.insertText( '@', doc.selection.getFirstPosition() );
+					} );
+
+					return waitForDebounce()
+						.then( () => {
+							expectChildViewsIsOnState( [ true, false, false, false, false ] );
```
Comment (mlewand) [inline tests/mentionui.js]: This unit test should be simplified. It should only focus on testing what's in the description, so case with a single item and pressing down/up arrow keys. No need to make test step to test all the items.

So the line https://github.com/ckeditor/ckeditor5-mention/blob/fe2b5c0/tests/mentionui.js#L916 should be more like:

```js
writer.insertText( '@T', doc.selection.getFirstPosition() );
```

And lines https://github.com/ckeditor/ckeditor5-mention/blob/fe2b5c0/tests/mentionui.js#L920-L930 should be removed.

Comment (jodator) [reply tests/mentionui.js]: Sure, looks like I've copy-pasted too much :D
