### PR TITLE
T/4: Add debounce mechanism.

### LINKED ISSUE #44: Cannot type mention inside brackets, quotes and after a soft break
Try to open mention's feed after typing `(@`. At this moment it does not work.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Type: Add debounce mechanism for requesting a feed. Closes ckeditor/ckeditor5#4619.

---

### Additional information

* This PR solves the problem of asynchronous server by:
    * Adding a debounce mechanism for requesting a feed (relatively short - `100ms` so if the feed callback promise resolves within 100-150ms [it should still be perceived as "fast"](https://www.nngroup.com/articles/response-times-3-important-limits/). - note that toolbar plugin is [debounced to 200ms](https://github.com/ckeditor/ckeditor5-ui/blob/ffec16ab9ec48edd68a076c69c646a2a5a9a7b0a/src/toolbar/balloon/balloontoolbar.js#L86).
    * Handling errors and request out-of-order problems by:
        *  discarding all but last requested feed (the comparison i relatively simple - just remember the last requested feed (the text for it) and if the response is not for this feed discard it
        * showing warning notification for any errors that ocured in feed callback (most likely due to communication/connectivity problems)

### CODE REVIEW

**Comment by jodator** [comment]
@Mgsy As this is issue should be prone to manual tests please take a look at the new manual tests for asynchronous feeds in mentions (others should work too).

@mlewand What is done is in the description but I've added a small follow up: #50 that can be resolved after this PR.

**Comment by jodator** [comment]
Edge.... :(

**Comment by jodator** [comment]
:crossed_fingers: last fixes to the test were pushed - hopefully will be OK now.

**Comment by jodator** [comment]
Yay it's working - @mlewand ready for review then.

**Comment by Mgsy** [comment]
1. Go to http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.html.
1. Put the selection behind `@`.
1. Very quickly keep pressing <kbd>Backspace</kbd>, then <kbd>@</kbd>.

The editor crashes; can't reproduce it in other manual tests/sample in docs.

```
ckeditorerror.js:46 Uncaught (in promise) CKEditorError: marker-destroyed: Cannot use a destroyed marker instance. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-marker-destroyed
    at Marker.getRange (http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.js:50782:10)
    at target (http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.js:93125:57)
    at Function.getOptimalPosition [as _getOptimalPosition] (http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.js:112787:12)
    at BalloonPanelView.attachTo (http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.js:105157:58)
    at BalloonPanelView._startPinning (http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.js:105240:8)
    at BalloonPanelView.pin (http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.js:105206:8)
    at ContextualBalloon._show (http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.js:105888:13)
    at ContextualBalloon.add (http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.js:105814:8)
    at MentionUI._showUI (http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.js:93041:18)
    at http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.js:93003:12
```

bug_cke5

**Comment by Mgsy** [comment]
1. Go to http://localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.html.
1. Put the selection behind `@`.
1. Press <kbd>Spacebar</kbd>.
1. Press <kbd>@</kbd>.
1. Undo.

The editor crashes.

```
mapper.js:478 Uncaught (in promise) TypeError: Cannot read property 'is' of undefined
    at Mapper._findPositionIn (mapper.js:478)
    at Mapper.on.priority (mapper.js:88)
    at Mapper.fire (emittermixin.js:207)
    at Mapper.toViewPosition (mapper.js:271)
    at Mapper.toViewRange (mapper.js:233)
    at target (mentionui.js:506)
    at Function.getOptimalPosition [as _getOptimalPosition] (position.js:84)
    at BalloonPanelView.attachTo (balloonpanelview.js:239)
    at BalloonPanelView._startPinning (balloonpanelview.js:322)
    at BalloonPanelView.pin (balloonpanelview.js:288)
```

bug_cke5

**Comment by Mgsy** [comment]
Sometimes the panel has an incorrect position:

bug_cke5

**Comment by Mgsy** [comment]
The edit link view appears after placing the selection inside a link while having the mentions panel opened on a different link.

bug_cke5

**Comment by jodator** [comment]
@Mgsy Could you recheck with reported errors? It looks like most of them are resolved.

@mlewand:  #67 is still therere though but it will be managed in a follow up.

**Comment by jodator** [comment]
@mlewand Ready for review with no crashes AFAICT (As Far As I Can Test).

**Comment by Mgsy** [comment]
The panel appears after changing selection before it shows up.

bug_cke5

**Comment by Mgsy** [comment]
1. Insert a new link element with `@` as text.
1. Put the caret behind the marker.
1. Immediately start pressing <kbd>Backspace</kbd>, then <kbd>@</kbd>.

Sometimes it crashes instantly, sometimes it requires a little more time.

bug_cke5


```
mapper.js:478 Uncaught TypeError: Cannot read property 'is' of undefined
    at Mapper._findPositionIn (mapper.js:478)
    at Mapper.on.priority (mapper.js:88)
    at Mapper.fire (emittermixin.js:207)
    at Mapper.toViewPosition (mapper.js:271)
    at Mapper.toViewRange (mapper.js:233)
    at target (mentionui.js:516)
    at Function.getOptimalPosition [as _getOptimalPosition] (position.js:84)
    at BalloonPanelView.attachTo (balloonpanelview.js:239)
    at BalloonPanelView._startPinning (balloonpanelview.js:322)
    at BalloonPanelView.pin (balloonpanelview.js:288)

log.js:72 rect-source-not-in-dom: The source of this rect does not belong to any rendered DOM tree. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-rect-source-not-in-dom
 {source: Range}

log.js:72 rect-source-not-in-dom: The source of this rect does not belong to any rendered DOM tree. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-rect-source-not-in-dom
 {source: a.ck-link_selected}

log.js:72 rect-source-not-in-dom: The source of this rect does not belong to any rendered DOM tree. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-rect-source-not-in-dom
 {source: Range}

rect.js:64 Uncaught TypeError: Cannot read property '_source' of null
    at new Rect (rect.js:64)
    at scrollAncestorsToShowRect (scroll.js:186)
    at scrollViewportToShowTarget (scroll.js:49)
    at View.scrollToTheSelection (view.js:376)
    at Document.<anonymous> (delete.js:42)
    at Document.fire (emittermixin.js:207)
    at Document.<anonymous> (deleteobserver.js:55)
    at Document.fire (emittermixin.js:207)
    at KeyObserver.fire (domeventobserver.js:96)
    at KeyObserver.onDomEvent (keyobserver.js:28)
```

**Comment by jodator** [comment]
@mlewand: So most of the problems were due to the removed marker from the model - either intentionally by Mention or by user action - and the `ContextualBalloon` plugin logic that uses old position data to place new panel.

The rationale there is to not jump the contextual balloon when views are switched - which makes sense. I'll create an issue in UI repo to allow `target()` method to return `undefined` and to properly handle such case (use another position).

For now I've added a fix to prevent using removed marker ranges - in such scenario the rect for selection will be returned.

**Comment by Mgsy** [comment]
The panel jumps after clicking on an item when the marker is a link.

bug_cke5

**Comment by jodator** [comment]
> **Edit:** Hmm, or is it the case you described above smile ?

Kinda is - internally the marker to which UI panel is positioned is removed so as described I have to return position to something - here this is selection - better would be to skip such positions (https://github.com/ckeditor/ckeditor5-ui/issues/503). I can see that after a while the panel is positioned to link anyway.

@mlewand:
Other possible fix is to change the marker management logic entirely. Do not ever remove the mention marker - only update it if need (but I'm not sure if such logic will be easy enough to implement as currently logic checks if marker exists on some occasions...

Anyway hopefully there's no red in console anymore :green_apple: :crossed_fingers:.

**Comment by jodator** [comment]
Last issue extracted to #72.

File: src/mentionui.js [hunk 1]
```diff
@@ -61,6 +70,55 @@ export default class MentionUI extends Plugin {
...
+
+					// At this point something bad happened - most likely unreachable host or some feed callback error.
+					// So cleanup marker, remove the UI and...
+					this._hideUIAndRemoveMarker();
+
+					const notification = editor.plugins.get( Notification );
+					const t = editor.locale.t;
+
+					// ...show warning notification.
+					notification.showWarning( t( 'Could not obtain mention autocomplete feed.' ), {
```
Comment (Reinmar) [inline src/mentionui.js]: At this moment we don't have notifications UI at all for CKE5 itself (it's available for Letters) so this will spit out alerts AFAIR. That'd be terrible.

In fact, using global notifications (even nice) for this case seems like overkill. For now I'd log this to the console and see if we need more.

Comment (jodator) [reply src/mentionui.js]: Short notice: the [`CKFinderCommand`](https://github.com/ckeditor/ckeditor5-ckfinder/blob/a4091a1e0f321cb93ebe036cd476969e328660cc/src/ckfindercommand.js#L110) uses also notifications so it might be a case for that also (blocking notifications).

File: src/mentionui.js [hunk 2]
```diff
@@ -61,6 +70,55 @@ export default class MentionUI extends Plugin {
...
+					this._hideUIAndRemoveMarker();
+
+					// ...log warning.
+					/**
+					 * The callback used for obtaining mention autocomplete feed thrown and error and the mention UI was hidden or
+					 * not displayed at all.
+					 *
+					 * @error mention-feed-callback-error
+					 */
+					log.warn( 'mention-feed-callback-error: Could not obtain mention autocomplete feed.' );
```
Comment (Reinmar) [inline src/mentionui.js]: The `log` object was removed. Please replace it with `console.warn()`.

**Comment by Reinmar** [comment]
Side topic: `handledKeyCodes` could be defined in the main module scope. Avoid allocating memory on every `isHandledKey()` execution.

File: src/mentionui.js [hunk 3]
```diff
@@ -61,6 +70,55 @@ export default class MentionUI extends Plugin {
 		this._mentionsConfigurations = new Map();
 
 		editor.config.define( 'mention', { feeds: [] } );
+
+		this._requestFeedDebounced = debounce( ( marker, feedText ) => {
+			this._getFeed( marker, feedText )
+				.catch( error => {
```
Comment (Reinmar) [inline src/mentionui.js]: Why do you define `catch()` before `then()`? For once, it's the opposite to how you think about error handling (1. do things, 2. handle errors). Plus, see "Exhibit A".

File: src/mentionui.js [hunk 4]
```diff
@@ -61,6 +70,55 @@ export default class MentionUI extends Plugin {
...
+					 *
+					 * @error mention-feed-callback-error
+					 */
+					log.warn( 'mention-feed-callback-error: Could not obtain mention autocomplete feed.' );
+				} )
+				.then( feed => {
+					// Do nothing if :
+					// - feed was discarded or empty feed was passed.
+					// - if the marker is not in the document - the selection might have already changed.
+					if ( !feed || !this.editor.model.markers.has( 'mention' ) ) {
```
Comment (Reinmar) [inline src/mentionui.js]: Exhibit A.

Why do we get to `.then()` if something went wrong? This should be handled earlier (in `_getFeed()` most likely).

File: src/mentionui.js [hunk 5]
```diff
@@ -61,6 +70,55 @@ export default class MentionUI extends Plugin {
...
+					/**
+					 * The callback used for obtaining mention autocomplete feed thrown and error and the mention UI was hidden or
+					 * not displayed at all.
+					 *
+					 * @error mention-feed-callback-error
+					 */
+					log.warn( 'mention-feed-callback-error: Could not obtain mention autocomplete feed.' );
+				} )
+				.then( feed => {
+					// Do nothing if :
```
Comment (Reinmar) [inline src/mentionui.js]:
```suggestion
					// Do nothing if:
```

File: src/mentionui.js [hunk 6]
```diff
@@ -61,6 +70,55 @@ export default class MentionUI extends Plugin {
 		this._mentionsConfigurations = new Map();
 
 		editor.config.define( 'mention', { feeds: [] } );
+
+		this._requestFeedDebounced = debounce( ( marker, feedText ) => {
```
Comment (Reinmar) [inline src/mentionui.js]: I found this bit of code slightly too hard to read due to a long callback for `debounce()`. I'd either move it outside or shortened the code inside it.

File: src/mentionui.js [hunk 7]
```diff
@@ -254,15 +305,39 @@ export default class MentionUI extends Plugin {
...
+		this._lastRequested = feedText;
+
+		// To unify later processing the _getFeed should return a promise even if feed callback returns an array.
+		return new Promise( ( resolve, reject ) => {
+			const response = feedCallback( feedText );
+
+			const isAsynchronous = response instanceof Promise;
+
+			if ( !isAsynchronous ) {
+				resolve( response );
```
Comment (Reinmar) [inline src/mentionui.js]: You forgot about an early return here... which opens a question – how does this even work and how is it possible that it didn't yield any errors?

File: src/mentionui.js [hunk 8]
```diff
@@ -254,15 +305,39 @@ export default class MentionUI extends Plugin {
...
+			}
+
+			response
+				.then( response => {
+					if ( this._lastRequested == feedText ) {
```
Comment (Reinmar) [inline src/mentionui.js]: Explanation needed.

File: src/mentionui.js (hunk 4 above)
Comment (Reinmar) [reply src/mentionui.js]: Also, since `marker` is available here by its instance, it may be confusing why you need to check it in the markers collection. I guess that that's because something might've changed in the content and this marker might've been removed? But there should be API methods that you use here to check that and those API methods would then clarify why you need to do so. E.g. it would be `checkIfStillInCompletionMode()` or something similar.

File: src/mentionui.js [hunk 9]
```diff
@@ -61,6 +70,55 @@ export default class MentionUI extends Plugin {
...
+					// Remove old entries.
+					this._items.clear();
+
+					for ( const feedItem of feed ) {
+						const item = typeof feedItem != 'object' ? { id: feedItem, text: feedItem } : feedItem;
+
+						this._items.add( { item, marker } );
+					}
+
+					const markerMarker = editor.model.markers.get( 'mention' );
```
Comment (Reinmar) [inline src/mentionui.js]: WAT?

File: src/mentionui.js [hunk 10]
```diff
@@ -61,6 +70,55 @@ export default class MentionUI extends Plugin {
...
+
+					if ( this._items.length && markerMarker ) {
+						this._showUI( markerMarker );
```
Comment (Reinmar) [inline src/mentionui.js]: What if the UI was already visible before this?

File: src/mentionui.js (hunk 3 above)
Comment (jodator) [reply src/mentionui.js]: I've refactored the MentionUI to events... dunno why I didn't that before - it is much better now IMO.

File: src/mentionui.js (hunk 9 above)
Comment (jodator) [reply src/mentionui.js]: I have a few laughs on this (probably the marker name was different then). Renamed that.

File: src/mentionui.js (hunk 10 above)
Comment (jodator) [reply src/mentionui.js]: I've renamed the method to make it clear what it does.

File: src/mentionui.js (hunk 4 above)
Comment (jodator) [reply src/mentionui.js]: I need to re-verify that - I do another round of self-review on this tomorrow.

**Comment by jodator** [comment]
@Reinmar thanks for the insights. I've cleaned up the code a bit but still, some minor work is needed:
1. Add tests for updating a marker.
2. Check some ifs if they cannot have some better code (e.g. adding `isInCompletionMode()` check).
3. Document the events.

But if feel free to check the code again if you wish - I don't think that much will change :)

**Comment by jodator** [comment]
@Mgsy Could you please re-check this PR as [before](https://github.com/ckeditor/ckeditor5-mention/pull/65#issuecomment-490883276)? This should work the same - ie no errors, etc. The code was refactored but it looks like everything works as expected.

@Reinmar So it is ready to review. The only thing that I've wanted to ask is should we expose events? I'm not sure if they are important to others. Right now they are documented but without much fuzz around them.

**Comment by jodator** [comment]
@mlewand the PR is OK now

**Comment by FilipTokarski** [comment]
Tested on all browsers, seems to work fine now 👍
