### PR TITLE
PR: Add single view mode to the contextual balloon.

### LINKED ISSUE #74: Mentions does not works well with the rotator
After https://github.com/ckeditor/ckeditor5-mention/issues/67 was closed I tested how mentions work with the rotator and unfortunately it does not work well:

mentions-rotator

Issues:
1. Error in the console:
```
rect.js:72 Uncaught (in promise) TypeError: Cannot read property '_source' of null
    at new Rect (rect.js:72)
    at MentionsView._isItemVisibleInScrolledArea (mentionsview.js:127)
    at MentionsView.select (mentionsview.js:109)
    at MentionsView.selectFirst (mentionsview.js:48)
    at MentionUI._showUI (mentionui.js:397)
    at eval (mentionui.js:351)
```
2. Mentions appears behind comment.
3. There is rotator above suggested options.

I believe when mentions balloon appears it should be one and only panel to be displayed.

After the talk with @jodator, we agreed it should be solved as a part of the Contextual Balloon. There should be a flag to prevent other stacks to be displayed.

I think we should have something like this:

`contextualBalloon.add( { view, preventOtherStacks = true } )`.

It should not remove any stacks from the contextualBalloon data, but prevent them from being displayed as long as the view with `preventOtherStacks` is added.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: The mention toolbar should be displayed as single view in contextual balloon. Closes #74.

---

### Additional information

This PR comes with constellation of changes on [ckeditor5#t/ckeditor5-mention/74](https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-mention/74) branch [Build Status](https://travis-ci.org/ckeditor/ckeditor5). 

which includes:

* Changes in the ui - added single view mode option to contextualballoon.add(): https://github.com/ckeditor/ckeditor5-ui/pull/507.

### CODE REVIEW

File: src/mentionui.js [hunk 1]
```diff
@@ -374,7 +374,9 @@ export default class MentionUI extends Plugin {
 			this._balloon.add( {
 				view: this._mentionsView,
 				position: this._getBalloonPanelPositionData( markerMarker, this._mentionsView.position ),
-				withArrow: false
+				withArrow: false,
+				singleViewMode: true,
+				stack: 'mention'
```
Comment (Reinmar) [inline src/mentionui.js]: Why is this needed?

Comment (jodator) [reply src/mentionui.js]: The `stack` or whole `singleViewMode`? Without the `stack` the mention panel would be added to the `'main'` stack. As the mention ui should be displayed in single view mode I recon that adding it to a separate stack would add separation from other features.

Comment (Reinmar) [reply src/mentionui.js]: What kind of separation? Doesn't `singleViewMode` guarantee complete separation already?

Comment (jodator) [reply src/mentionui.js]: Separation of stacks: Without `stack: 'mention'` it still would be displayed as a single view but internally it will reside in a stack with other features. 

So adding a new stack for single view is not obligatory I feel that it is much cleaner to have own stack for SVM rather then using `'main'` stack.

Comment (pjasiun) [reply src/mentionui.js]: I also do not know why you need to define a separate stack here. Also, the property is `stackId` not `stack` and the fact that it works fine with the wrong property proved that it is not needed ;)

Comment (jodator) [reply src/mentionui.js]: :man_facepalming: on me then

Comment (Reinmar) [reply src/mentionui.js]: I've got a good smell, then ;) Please remove it on master.

Comment (jodator) [reply src/mentionui.js]: done
